INSERT INTO public_error_map (pem_error_code, pem_error_msg) VALUES ('error01', '系统繁忙');
INSERT INTO public_error_map (pem_error_code, pem_error_msg) VALUES ('login_err_1', '密码错误');
INSERT INTO public_error_map (pem_error_code, pem_error_msg) VALUES ('login_err_2', '登录异常:其他错误');
INSERT INTO public_error_map (pem_error_code, pem_error_msg) VALUES ('NOT_FOUND_ERROR', '未查到记录');

INSERT INTO td_router (tr_router_id, tr_router_uri, tr_predicate_name, tr_predicate_args, tr_filters_name, tr_filters_args, tr_pattern, tr_order) VALUES ('route_evy_deploy_centre', 'lb://EVY-DEPLOY-CENTRE', 'Path', '{"patterns":"/evy-deploy-centre/**"}', 'StripPrefix', '{"parts":"1"}', '/evy-deploy-centre/**', '0');

INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.auto.app', 'com.evy.linlin.deploy.app.AutoDeployAppService', 'autoDeploy#/autoDeploy', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.buildPjo.app', 'com.evy.linlin.deploy.app.BuildProjectAppService', 'buildJar#/buildJar', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.create.app', 'com.evy.linlin.deploy.app.CreateDeployInfoAppService', 'create#/create', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.getBranch.app', 'com.evy.linlin.deploy.app.GetGitBrchansAppService', 'getGitBrchans#/getGitBrchans', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.nextSeq.app', 'com.evy.linlin.deploy.app.NextBuildSeqAppService', 'nextBuildSeq#/nextBuildSeq', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.qryDeployInfo.app', 'com.evy.linlin.deploy.app.QryDeployInfosAppService', 'qryDeployInfosByUser#/qryDeployInfosByUser', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.review.app', 'com.evy.linlin.deploy.app.ReviewDeployStatusAppService', 'reviewStatus#/reviewStatus', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.login.app', 'com.evy.linlin.login.app.LoginAppService', 'login#/login', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.memory.app', 'com.evy.linlin.trace.app.QryAppMermoryInfoAppService', 'qryAppMemoryList#/qryAppMemoryList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.httpQry.app', 'com.evy.linlin.trace.app.QryHttpInfoAppService', 'qryHttpInfoList#/qryHttpInfoList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.mqQry.app', 'com.evy.linlin.trace.app.QryMqTraceInfoAppService', 'qryMqTraceInfoList#/qryMqTraceInfoList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.redisQry.app', 'com.evy.linlin.trace.app.QryRedisInfoAppService', 'qryRedisInfoList#/qryRedisInfoList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.srvQry.app', 'com.evy.linlin.trace.app.QryServiceInfoAppService', 'qryServiceInfoList#/qryServiceInfoList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.slowSqlQry.app', 'com.evy.linlin.trace.app.QrySlowSqlInfoAppService', 'qrySlowSqlInfoList#/qrySlowSqlInfoList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.threadQry.app', 'com.evy.linlin.trace.app.QryThreadsInfoAppService', 'qryThreadsInfo#/qryThreadsInfo', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.srv.create', 'com.evy.linlin.trace.app.CreateSrvInfoAppService', 'createSrvInfo#/createSrvInfo', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.srv.modify', 'com.evy.linlin.trace.app.ModifySrvInfoAppService', 'modifySrvInfo#/modifySrvInfo', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.trackingQry.app', 'com.evy.linlin.trace.app.QryTrackingInfoAppService', 'qryTraceList#/qryTraceList', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.trace.dump.app', 'com.evy.linlin.trace.app.QryDumpInfoAppService', 'findDeadThreads#/findDeadThreads|heapDump#/heapDump|threadDump#/threadDump', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');
INSERT INTO trace_services_info (tsi_service_bean_name, tsi_service_name, tsi_service_path, tsi_provider, tsi_consumer, tsi_provider_names, tsi_consumer_names) VALUES ('evy.deploy.checkStart.app', 'com.evy.linlin.deploy.app.CheckStartAppService', 'checkStart#/checkStart', 'evy-deploy-centre', 'evy-gateway', 'evy-deploy-centre@127.0.0.1', 'evy-gateway@127.0.0.1');